/*
Post-Deployment Script Template							
--------------------------------------------------------------------------------------
 This file contains SQL statements that will be appended to the build script.		
 Use SQLCMD syntax to include a file in the post-deployment script.			
 Example:      :r .\myfile.sql								
 Use SQLCMD syntax to reference a variable in the post-deployment script.		
 Example:      :setvar TableName MyTable							
               SELECT * FROM [$(TableName)]					
--------------------------------------------------------------------------------------
*/
IF NOT EXISTS (SELECT * FROM [dbo].[Coberturas])
BEGIN
    INSERT INTO [dbo].[Coberturas](Sigla,RNOS,Cobertura) VALUES
     ('OSSEG','901','OBRA SOCIAL DE LA ACTIVIDAD DE SEGUROS, REASEGUROS, CAPITALIZACION Y AHORRO Y PRESTAMO PARA LA VIVIENDA')
    ,(NULL,'117801','OBRA SOCIAL DEL PERSONAL DE PRENSA DE MENDOZA')
    ,('ADOS','600408','ASOCIACION DE OBRAS SOCIALES DE COMODORO RIVADAVIA')
    ,('ADOS','601203','ASOCIACION DE OBRAS SOCIALES DE GUALEGUAY')
    ,('ADOS','602305','ASOCIACION DE OBRAS SOCIALES DE ROSARIO')
    ,('ADOS','603100','ASOCIACION DE OBRAS SOCIALES DE TRELEW')
    ,('ADOS','601104','ASOCIACION GUALEGUAYCHU DE OBRAS SOCIALES')
    ,('AMUR','900300','ASOCIACION MUTUAL RURALISTA')
    ,('INSSJP (PAMI)','500807','INSTITUTO NACIONAL DE SERVICIOS SOCIALES PARA JUBILADOS Y PENSIONADOS')
    ,(NULL,'703','MUTUAL DEL PERSONAL DEL AGUA Y LA ENERGIA DE MENDOZA')
    ,(NULL,'303307','OBRA SOCIAL CABOT ARGENTINA')
    ,('OSDEPYM','401704','OBRA SOCIAL DE EMPRESARIOS, PROFESIONALES Y MONOTRIBUTISTAS')
    ,('OSPYSA','3801','OBRA SOCIAL DE LA PREVENCION Y LA SALUD')
    ,('OSUTHGRA','108803','OBRA SOCIAL DE LA UNION DE TRABAJADORES DEL TURISMO, HOTELEROS Y GASTRONOMICOS DE LA REPUBLICA ARGENTINA')
    ,('OSEADI','100908','OBRA SOCIAL EMPLEADOS DE AGENCIAS DE INFORMES')
    ,('OSPIFSE','108001','OBRA SOCIAL PARA EL PERSONAL DE LA INDUSTRIA FORESTAL DE SANTIAGO DEL ESTERO')
    ,('OSYC','3702','OBRA SOCIAL YACIMIENTOS CARBONIFEROS')
    ,('OSAP','800501','OBRA SOCIAL ACEROS PARANA')
    ,('OSAMOC','3405','OBRA SOCIAL ASOCIACION MUTUAL DE LOS OBREROS CATOLICOS PADRE FEDERICO GROTE')
    ,('ASSPE','402608','OBRA SOCIAL ASOCIACION DE SERVICIOS SOCIALES PARA EMPRESARIOS Y PERSONAL DE DIRECCION DE EMPRESAS DEL COMERCIO, SERVICIOS, PRODUCCION, INDUSTRIA Y CIVIL')
    ,('APDIS','402103','OBRA SOCIAL ASOCIACION DEL PERSONAL DE DIRECCION DE LA INDUSTRIA SIDERURGICA')
    ,('APSOT','402301','OBRA SOCIAL ASOCIACION DEL PERSONAL SUPERIOR DE LA ORGANIZACION TECHINT')
    ,('AMPAR','401803','OBRA SOCIAL ASOCIACION MUTUAL DEL PERSONAL DE PHILIPS ARGENTINA')
    ,('OSAMMVC','2907','OBRA SOCIAL ASOCIACION MUTUAL METALURGICA VILLA CONSTITUCION')
    ,('OSCAPBAQFLU','111506','OBRA SOCIAL ASOCIACION PROFESIONAL DE CAPITANES Y BAQUEANOS FLUVIALES Y PERSONAL CON CONOCIMIENTO DE ZONA DE LA MARINA MERCANTE')
    ,('JOHNSON','300704','OBRA SOCIAL CERAS JOHNSON')
    ,('OSTC','121804','OBRA SOCIAL CONDUCTORES DE TAXIS DE CORDOBA')
    ,('OSCTCP','121606','OBRA SOCIAL CONDUCTORES DE TRANSPORTE COLECTIVO DE PASAJEROS')
    ,('CAMPSIC','400305','OBRA SOCIAL COOPERATIVA LTDA. DE ASISTENCIA MEDICA Y FARMACEUTICA, SERVICIOS ASISTENCIALES Y TURISMO DEL PERSONAL SUPERIOR DE LA INDUSTRIA DEL CAUCHO Y OTRAS ACTIVIDADES INDUSTRIALES')
    ,('OSEIV','122401','OBRA SOCIAL DE EMPLEADOS DE LA INDUSTRIA DEL VIDRIO')
    ,('OSADEF','127505','OBRA SOCIAL DE LAS ASOCIACIONES DE EMPLEADOS DE FARMACIA')
    ,('OSA','100205','OBRA SOCIAL DE ACTORES')
    ,('OSA','100809','OBRA SOCIAL DE AERONAVEGANTES')
    ,('OSALARA','604','OBRA SOCIAL DE AGENTES DE LOTERIAS Y AFINES DE LA REPUBLICA ARGENTINA')
    ,('OSAPMCBA','118309','OBRA SOCIAL DE AGENTES DE PROPAGANDA MEDICA DE CORDOBA')
    ,('OSAPMER','118408','OBRA SOCIAL DE AGENTES DE PROPAGANDA MEDICA DE ENTRE RIOS')
    ,('OSAPM','118200','OBRA SOCIAL DE AGENTES DE PROPAGANDA MEDICA DE LA REPUBLICA ARGENTINA')
    ,('OSADRA','125905','OBRA SOCIAL DE ARBITROS DEPORTIVOS DE LA REPUBLICA ARGENTINA')
    ,('OSBARA','124001','OBRA SOCIAL DE BOXEADORES AGREMIADOS DE LA REPUBLICA ARGENTINA')
    ,('OSCEP','116105','OBRA SOCIAL DE CAPATACES ESTIBADORES PORTUARIOS')
    ,('OSCOMM','111407','OBRA SOCIAL DE CAPITANES DE ULTRAMAR Y OFICIALES DE LA MARINA MERCANTE')
    ,('OSPESCA','505','OBRA SOCIAL DE CAPITANES, PILOTOS Y PATRONES DE PESCA')
    ,('OSCE','104108','OBRA SOCIAL DE CERAMISTAS')
    ,('OSCHOCA','105804','OBRA SOCIAL DE CHOFERES DE CAMIONES')
    ,('OSCAMGLYP','104801','OBRA SOCIAL DE COLOCADORES DE AZULEJOS, MOSAICOS, GRANITEROS, LUSTRADORES Y PORCELANEROS')
    ,('OSOCNA','113809','OBRA SOCIAL DE COMISARIOS NAVALES')
    ,('OSCCPTAC','103204','OBRA SOCIAL DE CONDUCTORES CAMIONEROS Y PERSONAL DEL TRANSPORTE AUTOMOTOR DE CARGAS')
    ,('OSCRAIA','126809','OBRA SOCIAL DE CONDUCTORES DE REMISES Y AUTOS AL INSTANTE Y AFINES')
    ,('OSCONARA','105002','OBRA SOCIAL DE CONDUCTORES NAVALES')
    ,('OSTAXBA','3504','OBRA SOCIAL DE CONDUCTORES TITULARES DE TAXIS DE LA CIUDAD AUTONOMA DE BUENOS AIRES')
    ,('OSDAAP','402806','OBRA SOCIAL DE DIRECCION DE LA ACTIVIDAD AEROCOMERCIAL PRIVADA')
    ,('OSDO','402707','OBRA SOCIAL DE DIRECCION')
    ,('OSDOP','106302','OBRA SOCIAL DE DOCENTES PARTICULARES')
    ,('OSDE','400800','OBRA SOCIAL DE EJECUTIVOS Y DEL PERSONAL DE DIRECCION DE EMPRESAS')
    ,('OSEDA','106104','OBRA SOCIAL DE EMPLEADOS DE DESPACHANTES DE ADUANA')
    ,('OSEMM','111605','OBRA SOCIAL DE EMPLEADOS DE LA MARINA MERCANTE')
    ,('OSEPC','118002','OBRA SOCIAL DE EMPLEADOS DE PRENSA DE CORDOBA')
    ,('OSETRA','120603','OBRA SOCIAL DE EMPLEADOS DEL TABACO DE LA REPUBLICA ARGENTINA')
    ,('OSETYA','121101','OBRA SOCIAL DE EMPLEADOS TEXTILES Y AFINES')
    ,('OSEPJANA','2204','OBRA SOCIAL DE EMPLEADOS Y PERSONAL JERARQUICO DE LA ACTIVIDAD DEL NEUMATICO ARGENTINO DE NEUMATICOS GOOD YEAR SRL')
    ,('OSEAM','111704','OBRA SOCIAL DE ENCARGADOS APUNTADORES MARITIMOS')
    ,('OSFYB','128508','OBRA SOCIAL DE FARMACEUTICOS Y BIOQUIMICOS')
    ,('OSF','1904','OBRA SOCIAL DE FEDECAMARAS')
    ,(NULL,'303901','OBRA SOCIAL DE FORD ARGENTINA S.C.A.')
    ,('OSFOT','108209','OBRA SOCIAL DE FOTOGRAFOS')
    ,('FAA','108605','OBRA SOCIAL DE FUTBOLISTAS')
    ,('OSGUIN','109202','OBRA SOCIAL DE GUINCHEROS Y MAQUINISTAS DE GRUAS MOVILES')
    ,('OSJPVYF','110107','OBRA SOCIAL DE JARDINEROS, PARQUISTAS, VIVERISTAS Y FLORICULTORES DE LA REPUBLICA ARGENTINA')
    ,('OSJOMN','113304','OBRA SOCIAL DE JEFES Y OFICIALES MAQUINISTAS NAVALES')
    ,('OSJONR','113205','OBRA SOCIAL DE JEFES Y OFICIALES NAVALES DE RADIOCOMUNICACIONES')
    ,('OSAM','112400','OBRA SOCIAL DE LA ACTIVIDAD MINERA')
    ,('OSSACRA','1508','OBRA SOCIAL DE LA ASOCIACION CIVIL PROSINDICATO DE AMAS DE CASA DE LA REPUBLICA ARGENTINA')
    ,('APDJIC','400503','OBRA SOCIAL DE LA ASOCIACION DEL PERSONAL DE DIRECCION Y JERARQUICO DE LA INDUSTRIA DEL CIGARRILLO')
    ,('OSAPSE','129006','OBRA SOCIAL DE LA ASOCIACION DEL PERSONAL SUPERIOR DE LA EMPRESA PROVINCIAL DE ENERGIA DE CORDOBA')
    ,('OSCEARA','2808','OBRA SOCIAL DE LA CAMARA DE EMPRESARIOS DE AGENCIAS DE REMISES DE ARGENTINA')
    ,('OSCOEMA','126502','OBRA SOCIAL DE LA CONFEDERACION DE OBREROS Y EMPLEADOS MUNICIPALES ARGENTINA')
    ,('OSFATLYF','110701','OBRA SOCIAL DE LA FEDERACION ARGENTINA DE TRABAJADORES DE LUZ Y FUERZA')
    ,('OSFATUN','125509','OBRA SOCIAL DE LA FEDERACION ARGENTINA DEL TRABAJADOR DE LAS UNIVERSIDADES NACIONALES')
    ,(NULL,'126007','OBRA SOCIAL DE LA FEDERACION GREMIAL DEL PERSONAL DE LA INDUSTRIA DE LA CARNE Y SUS DERIVADOS')
    ,('OSIPA','114208','OBRA SOCIAL DE LA INDUSTRIA DE PASTAS ALIMENTICIAS')
    ,('OSITAC','121507','OBRA SOCIAL DE LA INDUSTRIA DEL TRANSPORTE  AUTOMOTOR DE CORDOBA')
    ,('OSUTI','128102','OBRA SOCIAL DE LA UNION DE TRABAJADORES DEL INSTITUTO NACIONAL DE SERVICIOS SOCIALES PARA JUBILADOS Y PENSIONADOS DE LA REPUBLICA ARGENTINA')
    ,('OSUOMRA','112103','OBRA SOCIAL DE LA UNION OBRERA METALURGICA DE LA REPUBLICA ARGENTINA')
    ,('OSDEL','110602','OBRA SOCIAL DE LOCUTORES')
    ,('OSLERA','1805','OBRA SOCIAL DE LOS  LEGISLADORES DE LA REPUBLICA ARGENTINA')
    ,('OSSIMRA','112202','OBRA SOCIAL DE LOS  SUPERVISORES DE LA INDUSTRIA METALMECANICA DE LA REPUBLICA ARGENTINA')
    ,('OSUCI','105507','OBRA SOCIAL DE LOS CORTADORES DE LA INDUMENTARIA')
    ,('OSECAC','126205','OBRA SOCIAL DE LOS EMPLEADOS DE COMERCIO Y ACTIVIDADES CIVILES')
    ,('OSPAÑA','3108','OBRA SOCIAL DE LOS INMIGRANTES ESPAÑOLES Y SUS DESCENDIENTES RESIDENTES EN LA REPUBLICA ARGENTINA')
    ,('OSMEDICA','126908','OBRA SOCIAL DE LOS MEDICOS DE LA CIUDAD DE BUENOS AIRES')
    ,('OSPUAYE','125103','OBRA SOCIAL DE LOS PROFESIONALES UNIVERSITARIOS DEL AGUA Y LA ENERGIA ELECTRICA')
    ,('OSTACC,','128904','OBRA SOCIAL DE LOS TRABAJADORES ARGENTINOS DE CENTROS DE CONTACTOS')
    ,('OSTAMMA','2709','OBRA SOCIAL DE LOS TRABAJADORES ASOCIADOS A LA ASOCIACION MUTUAL MERCANTIL ARGENTINA')
    ,('OSTCARA','2600','OBRA SOCIAL DE LOS TRABAJADORES DE LA CARNE Y AFINES DE LA REPUBLICA ARGENTINA')
    ,('OSTEE','110800','OBRA SOCIAL DE LOS TRABAJADORES DE LAS EMPRESAS DE ELECTRICIDAD')
    ,(NULL,'127307','OBRA SOCIAL DE LOS TRABAJADORES VIALES Y AFINES DE LA REPUBLICA ARGENTINA')
    ,('OSLYF PATAGONIA','127802','OBRA SOCIAL DE LUZ Y FUERZA DE LA PATAGONIA')
    ,('OSMMEDT','127208','OBRA SOCIAL DE MANDOS MEDIOS DE TELECOMUNICACIONES EN LA REPUBLICA ARGENTINA Y MERCOSUR')
    ,(NULL,'111308','OBRA SOCIAL DE MAQUINISTAS DE TEATRO Y TELEVISION')
    ,('OSMISS','2501','OBRA SOCIAL DE MINISTROS, SECRETARIOS Y SUBSECRETARIOS')
    ,('OSDEM','112806','OBRA SOCIAL DE MUSICOS')
    ,(NULL,'106708','OBRA SOCIAL DE OBREROS EMPACADORES DE FRUTA  DE RIO NEGRO Y NEUQUEN')
    ,('OSOETSYLARA','127406','OBRA SOCIAL DE OBREROS Y EMPLEADOS TINTOREROS SOMBREREROS Y LAVADEROS DE LA REPUBLICA ARGENTINA')
    ,(NULL,'114901','OBRA SOCIAL DE OFICIALES PELUQUEROS Y PEINADORES  DE LA 2DA CIRCUNSCRIPCION JUDICIAL DE LA PROVINCIA DE SANTA FE')
    ,('OSOC','104603','OBRA SOCIAL DE OPERADORES CINEMATOGRAFICOS')
    ,('OSSPYFER','114000','OBRA SOCIAL DE PANADEROS, PASTELEROS Y FACTUREROS DE ENTRE RIOS')
    ,(NULL,'114505','OBRA SOCIAL DE PATRONES DE CABOTAJE DE RIOS Y PUERTOS')
    ,('OSPETAX','123701','OBRA SOCIAL DE PEONES DE TAXIS DE LA CAPITAL FEDERAL')
    ,('OSPE','115300','OBRA SOCIAL DE PETROLEROS')
    ,('OSPECOR','115508','OBRA SOCIAL DE PETROLEROS DE CORDOBA')
    ,('OSPEPRI','127901','OBRA SOCIAL DE PETROLEROS PRIVADOS')
    ,('OSPA','116204','OBRA SOCIAL DE PORTUARIOS ARGENTINOS')
    ,('OSRGA','118804','OBRA SOCIAL DE RECIBIDORES DE GRANOS Y ANEXOS')
    ,('OSRJA','119203','OBRA SOCIAL DE RELOJEROS Y JOYEROS')
    ,(NULL,'119906','OBRA SOCIAL DE SERENOS DE BUQUES')
    ,(NULL,'303406','OBRA SOCIAL DE SHELL ARGENTINA')
    ,('OSTECF','108704','OBRA SOCIAL DE TECNICOS DE FUTBOL')
    ,('OSTVLA','3900','OBRA SOCIAL DE TECNICOS DE VUELO DE LINEAS AEREAS')
    ,('OSTES','127000','OBRA SOCIAL DE TRABAJADORES DE ESTACIONES DE SERVICIO')
    ,('OSTIG','124506','OBRA SOCIAL DE TRABAJADORES DE LA INDUSTRIA DEL GAS')
    ,('OSTRAC','120801','OBRA SOCIAL DE TRABAJADORES DE LAS COMUNICACIONES')
    ,('OSTP','123602','OBRA SOCIAL DE TRABAJADORES DE PERKINS ARGENTINA S.A.I.C')
    ,('OSTPBA','115102','OBRA SOCIAL DE TRABAJADORES DE PRENSA DE BUENOS AIRES')
    ,(NULL,'128607','OBRA SOCIAL DE TRABAJADORES DEL PETROLEO Y GAS PRIVADO DEL CHUBUT')
    ,(NULL,'3207','OBRA SOCIAL DE TRABAJADORES SOCIOS DE LA ASOCIACION MUTUAL DEL PERSONAL JERARQUICO DE BANCOS OFICIALES NACIONALES-JERARQUICOS SALUD-')
    ,('OSTVENDRA','3306','OBRA SOCIAL DE TRABAJADORES VENDEDORES DE DIARIOS REVISTAS Y AFINES')
    ,(NULL,'121903','OBRA SOCIAL DE VAREADORES')
    ,('OSVARA','123909','OBRA SOCIAL DE VENDEDORES AMBULANTES DE LA REPUBLICA ARGENTINA')
    ,('OSVVRA','122104','OBRA SOCIAL DE VIAJANTES VENDEDORES DE LA REPUBLICA ARGENTINA. (ANDAR)')
    ,(NULL,'304003','OBRA SOCIAL DE VOLKSWAGEN ARGENTINA S.A.')
    ,('OSPATCA','105309','OBRA SOCIAL DEL PERSONAL ADMINISTRATIVO Y TECNICO DE LA CONSTRUCCION Y AFINES')
    ,('OSPAD','128805','OBRA SOCIAL DEL PERSONAL ADUANERO DE LA REPUBLICA ARGENTINA')
    ,('OSPA','100502','OBRA SOCIAL DEL PERSONAL AERONAUTICO')
    ,('OSPERSAAMS','3009','OBRA SOCIAL DEL PERSONAL ASOCIADO A ASOCIACION MUTUAL SANCOR')
    ,('OSPACP','103600','OBRA SOCIAL DEL PERSONAL AUXILIAR DE CASAS PARTICULARES')
    ,('OSPERCIN','104405','OBRA SOCIAL DEL PERSONAL CINEMATOGRAFICO DE MAR DEL PLATA')
    ,('OSPEMOM','112301','OBRA SOCIAL DEL PERSONAL DE  MICROS Y OMNIBUS DE MENDOZA')
    ,('OSPADEP','100601','OBRA SOCIAL DEL PERSONAL DE AERONAVEGACION DE ENTES PRIVADOS')
    ,('OSPAGA','101000','OBRA SOCIAL DEL PERSONAL DE AGUAS GASEOSAS Y AFINES')
    ,(NULL,'102904','OBRA SOCIAL DEL PERSONAL DE BARRACAS DE LANAS, CUEROS Y ANEXOS')
    ,('OSPCYD','103402','OBRA SOCIAL DEL PERSONAL DE CARGA Y DESCARGA')
    ,('OSPCRA','104009','OBRA SOCIAL DEL PERSONAL DE CEMENTERIOS DE LA REPUBLICA ARGENTINA.')
    ,('OSPEMER','109301','OBRA SOCIAL DEL PERSONAL DE CONSIGNATARIOS DEL MERCADO NACIONAL DE HACIENDA DE LINIERS')
    ,('ASE','400909','OBRA SOCIAL DEL PERSONAL DE DIRECCION  ACCION SOCIAL DE EMPRESARIOS (A:S:E.)')
    ,(NULL,'401100','OBRA SOCIAL DEL PERSONAL DE DIRECCION ALFREDO FORTABAT')
    ,('OSPDESBA','120405','OBRA SOCIAL DEL PERSONAL DE DIRECCION DE LA EMPRESA SUBTERRANEOS DE BUENOS AIRES')
    ,('OSPREME','400206','OBRA SOCIAL DEL PERSONAL DE DIRECCION DE LA INDUSTRIA AUTOMOTRIZ ARGENTINA')
    ,('SERVESALUD','400404','OBRA SOCIAL DEL PERSONAL DE DIRECCION DE LA INDUSTRIA CERVECERA Y MALTERA')
    ,('OSIM','401209','OBRA SOCIAL DEL PERSONAL DE DIRECCION DE LA INDUSTRIA METALURGICA  Y DEMAS ACTIVIDADES EMPRESARIAS')
    ,('OSDIPP','401605','OBRA SOCIAL DEL PERSONAL DE DIRECCION DE LA INDUSTRIA PRIVADA DEL PETROLEO')
    ,('OPDEA','400107','OBRA SOCIAL DEL PERSONAL DE DIRECCION DE LAS EMPRESAS DE LA ALIMENTACION Y DEMAS ACTIVIDADES EMPRESARIAS')
    ,('FRUTOS','401001','OBRA SOCIAL DEL PERSONAL DE DIRECCION DE LAS EMPRESAS QUE ACTUAN EN FRUTOS DEL PAIS')
    ,('WHOPE','401902','OBRA SOCIAL DEL PERSONAL DE DIRECCION DE PERFUMERIA E.W. HOPE')
    ,('OSLPASTEUR','402004','OBRA SOCIAL DEL PERSONAL DE DIRECCION DE SANIDAD LUIS PASTEUR')
    ,('OSPEDICI','106203','OBRA SOCIAL DEL PERSONAL DE DISTRIBUIDORAS CINEMATOGRAFICAS DE LA R.A.')
    ,('OSPEDYB','128706','OBRA SOCIAL DEL PERSONAL DE DRAGADO Y BALIZAMIENTO')
    ,('OSPERYH','106500','OBRA SOCIAL DEL PERSONAL DE EDIFICIOS DE RENTA Y HORIZONTAL DE LA CIUDAD AUTONOMA DE BUENOS AIRES  Y GRAN BUENOS AIRES')
    ,('OSPERYHRA','106401','OBRA SOCIAL DEL PERSONAL DE EDIFICIOS DE RENTA Y HORIZONTAL DE LA REPUBLICA ARGENTINA')
    ,('OSPEF Y EPCA','900102','OBRA SOCIAL DEL PERSONAL DE EMPRESAS FIAT Y EMPRESAS PEUGEOT CITROEN ARGENTINA')
    ,('OSPEDYC','106005','OBRA SOCIAL DEL PERSONAL DE ENTIDADES DEPORTIVAS Y CIVILES')
    ,('OSPEPBA','106906','OBRA SOCIAL DEL PERSONAL DE ESCRIBANIAS DE LA PROVINCIA DE BUENOS AIRES')
    ,('OSPE','107008','OBRA SOCIAL DEL PERSONAL DE ESCRIBANOS')
    ,('OSPESGYPE','107206','OBRA SOCIAL DEL PERSONAL DE ESTACIONES DE SERVICIO Y G.N.C, GARAGES, PLAYAS DE ESTACIONAMIENTO Y LAVADEROS AUTOMATICOS')
    ,('OSPESGA','122906','OBRA SOCIAL DEL PERSONAL DE ESTACIONES DE SERVICIO, GARAGES, PLAYAS Y LAVADEROS AUTOMATICOS DE LA PROVINCIA DE SANTA FE')
    ,('UPFPARA','115805','OBRA SOCIAL DEL PERSONAL DE FABRICAS DE PINTURA')
    ,('OSPF','107404','OBRA SOCIAL DEL PERSONAL DE FARMACIA')
    ,('OSPIDA','109707','OBRA SOCIAL DEL PERSONAL DE IMPRENTAS, DIARIOS Y AFINES')
    ,('OPZC','126601','OBRA SOCIAL DEL PERSONAL DE INDUSTRIAS  QUIMICAS Y PETROQUIMICAS DE ZARATE CAMPANA')
    ,('OSPIQYP','118705','OBRA SOCIAL DEL PERSONAL DE INDUSTRIAS QUIMICAS Y PETROQUIMICAS')
    ,('OSPIS','119609','OBRA SOCIAL DEL PERSONAL DE INSTALACIONES SANITARIAS')
    ,('OSPEJ','110008','OBRA SOCIAL DEL PERSONAL DE JABONEROS')
    ,(NULL,'126700','OBRA SOCIAL DEL PERSONAL DE LA ACTIVIDAD AZUCARERA TUCUMANA')
    ,('OSPACA','104306','OBRA SOCIAL DEL PERSONAL DE LA ACTIVIDAD CERVECERA Y AFINES')
    ,('OSPAT','121705','OBRA SOCIAL DEL PERSONAL DE LA ACTIVIDAD DEL TURF')
    ,('OSPAF','108407','OBRA SOCIAL DEL PERSONAL DE LA ACTIVIDAD FRUTICOLA')
    ,('OSPAP','115003','OBRA SOCIAL DEL PERSONAL DE LA ACTIVIDAD PERFUMISTA')
    ,('OSPA-VIAL','122302','OBRA SOCIAL DEL PERSONAL DE LA ACTIVIDAD VIAL')
    ,('OSPAV','122609','OBRA SOCIAL DEL PERSONAL DE LA ACTIVIDAD VITIVINICOLA')
    ,('OSPCSPMYA','104207','OBRA SOCIAL DEL PERSONAL DE LA CERAMICA, SANITARIOS, PORCELANA DE MESA Y AFINES')
    ,('OSPECON','105408','OBRA SOCIAL DEL PERSONAL DE LA CONSTRUCCION')
    ,('OSPEC','200400','OBRA SOCIAL DEL PERSONAL DE LA EMPRESA NACIONAL DE CORREOS Y TELEGRAFOS S.A. Y DE LAS  COMUNICACIONES DE LA REPULICA ARGENTINA')
    ,('OSPEP','106807','OBRA SOCIAL DEL PERSONAL DE LA ENSE�ANZA PRIVADA')
    ,(NULL,'128003','OBRA SOCIAL DEL PERSONAL DE LA FEDERACION DE SINDICATOS DE LA INDUSTRIA QUIMICA Y PETROQUIMICA')
    ,('OSPIT','120504','OBRA SOCIAL DEL PERSONAL DE LA INDUSTRIA  DEL TABACO')
    ,('OSPIA','102706','OBRA SOCIAL DEL PERSONAL DE LA INDUSTRIA AZUCARERA')
    ,('OSPIB','103006','OBRA SOCIAL DEL PERSONAL DE LA INDUSTRIA BOTONERA')
    ,('OSPIC','104504','OBRA SOCIAL DEL PERSONAL DE LA INDUSTRIA CINEMATOGRAFICA')
    ,('OSPIA','101208','OBRA SOCIAL DEL PERSONAL DE LA INDUSTRIA DE LA ALIMENTACION')
    ,('OSPICAL','103105','OBRA SOCIAL DEL PERSONAL DE LA INDUSTRIA DEL CALZADO')
    ,('OSPIC','103709','OBRA SOCIAL DEL PERSONAL DE LA INDUSTRIA DEL CAUCHO')
    ,('OSPIC SANTA FE','103907','OBRA SOCIAL DEL PERSONAL DE LA INDUSTRIA DEL CAUCHO DE SANTA FE')
    ,('OSPICHA','105705','OBRA SOCIAL DEL PERSONAL DE LA INDUSTRIA DEL CHACINADO Y AFINES')
    ,('OSPICA','105606','OBRA SOCIAL DEL PERSONAL DE LA INDUSTRIA DEL CUERO Y AFINES')
    ,('OSPIF','107800','OBRA SOCIAL DEL PERSONAL DE LA INDUSTRIA DEL FIBROCEMENTO')
    ,('OSPIF','108100','OBRA SOCIAL DEL PERSONAL DE LA INDUSTRIA DEL FOSFORO, ENCENDIDO Y AFINES')
    ,('OSPIHMP','109400','OBRA SOCIAL DEL PERSONAL DE LA INDUSTRIA DEL HIELO Y MERCADOS PARTICULARES')
    ,('OSPIN','113601','OBRA SOCIAL DEL PERSONAL DE LA INDUSTRIA DEL NEUMATICO')
    ,('OSPIP','115201','OBRA SOCIAL DEL PERSONAL DE LA INDUSTRIA DEL PESCADO DE MAR DEL PLATA')
    ,('OSPIP','116006','OBRA SOCIAL DEL PERSONAL DE LA INDUSTRIA DEL PLASTICO')
    ,('OSPIT','121309','OBRA SOCIAL DEL PERSONAL DE LA INDUSTRIA DEL TRACTOR')
    ,('OSPIV','122005','OBRA SOCIAL DEL PERSONAL DE LA INDUSTRIA DEL VESTIDO')
    ,('OSPIV','122500','OBRA SOCIAL DEL PERSONAL DE LA INDUSTRIA DEL VIDRIO')
    ,('OSPIF','107909','OBRA SOCIAL DEL PERSONAL DE LA INDUSTRIA FIDEERA')
    ,('OSPILM','110404','OBRA SOCIAL DEL PERSONAL DE LA INDUSTRIA LADRILLERA A MAQUINA')
    ,('OSPIL','110503','OBRA SOCIAL DEL PERSONAL DE LA INDUSTRIA LECHERA')
    ,('OSPIM','111001','OBRA SOCIAL DEL PERSONAL DE LA INDUSTRIA MADERERA')
    ,('OSPIM','112608','OBRA SOCIAL DEL PERSONAL DE LA INDUSTRIA MOLINERA')
    ,('OSPIN','113700','OBRA SOCIAL DEL PERSONAL DE LA INDUSTRIA NAVAL')
    ,('OSPIP','115607','OBRA SOCIAL DEL PERSONAL DE LA INDUSTRIA PETROQUIMICA')
    ,('OSPIT','121002','OBRA SOCIAL DEL PERSONAL DE LA INDUSTRIA TEXTIL')
    ,('OSPP','118606','OBRA SOCIAL DEL PERSONAL DE LA PUBLICIDAD')
    ,('OSPSA','119500','OBRA SOCIAL DEL PERSONAL DE LA SANIDAD ARGENTINA')
    ,('OSTEL','120702','OBRA SOCIAL DEL PERSONAL DE LAS TELECOMUNICACIONES DE LA REPUBLICA ARGENTINA')
    ,('OSPHGBAYSI','109509','OBRA SOCIAL DEL PERSONAL DE LOS HIPODROMOS DE BUENOS AIRES Y SAN ISIDRO')
    ,('OSLYF','110909','OBRA SOCIAL DEL PERSONAL DE LUZ Y FUERZA DE CORDOBA')
    ,('OSPM','111209','OBRA SOCIAL DEL PERSONAL DE MAESTRANZA')
    ,('OSFYHC','108506','OBRA SOCIAL DEL PERSONAL DE MANIPULEO, EMPAQUE Y EXPEDICION DE FRUTA FRESCA Y HORTALIZAS DE CUYO')
    ,('OSOSS','127604','OBRA SOCIAL DEL PERSONAL DE OBRAS Y SERVICIOS SANITARIOS')
    ,('OSPEP','113908','OBRA SOCIAL DEL PERSONAL DE PANADERIAS')
    ,(NULL,'303703','OBRA SOCIAL DEL PERSONAL DE PBBPOLISUR  SRL DE  BAHIA BLANCA')
    ,('OSPPEA','114703','OBRA SOCIAL DEL PERSONAL DE PELUQUERIAS, ESTETICAS Y AFINES')
    ,(NULL,'117405','OBRA SOCIAL DEL PERSONAL DE PRENSA DE BAHIA BLANCA')
    ,('OSPPRA','117207','OBRA SOCIAL DEL PERSONAL DE PRENSA DE LA REPUBLICA ARGENTINA')
    ,('OSPREN','117702','OBRA SOCIAL DEL PERSONAL DE PRENSA DE MAR DEL PLATA')
    ,('OSPRO','123404','OBRA SOCIAL DEL PERSONAL DE PRENSA DE ROSARIO')
    ,('OSPRENTUC','123503','OBRA SOCIAL DEL PERSONAL DE PRENSA DE TUCUMAN')
    ,(NULL,'118903','OBRA SOCIAL DEL PERSONAL DE RECOLECCION Y BARRIDO DE ROSARIO')
    ,(NULL,'119005','OBRA SOCIAL DEL PERSONAL DE REFINERIAS DE MAIZ')
    ,('OSPSIP','119708','OBRA SOCIAL DEL PERSONAL DE SEGURIDAD COMERCIAL, INDUSTRIAL E INVESTIGACIONES PRIVADAS')
    ,('OSPESA','123305','OBRA SOCIAL DEL PERSONAL DE SOCIEDADES DE AUTORES Y AFINES')
    ,('OSPSESBA','120306','OBRA SOCIAL DEL PERSONAL DE SUPERVISION DE LA EMPRESA SUBTERRANEOS DE BUENOS AIRES')
    ,('OSPETELCO','127109','OBRA SOCIAL DEL PERSONAL DE TELECOMUNICACIONES SINDICATO BUENOS AIRES')
    ,('OSPTV','120900','OBRA SOCIAL DEL PERSONAL DE TELEVISION')
    ,('OSPEVIC','122807','OBRA SOCIAL DEL PERSONAL DE VIGILANCIA Y SEGURIDAD COMERCIAL, INDUSTRIAL E INVESTIGACIONES PRIVADAS DE CORDOBA')
    ,('OSPACA','101604','OBRA SOCIAL DEL PERSONAL DEL AUTOMOVIL  CLUB ARGENTINO')
    ,('OSPA','101802','OBRA SOCIAL DEL PERSONAL DEL AZUCAR DEL INGENIO LA ESPERANZA')
    ,('OSPAIL','101901','OBRA SOCIAL DEL PERSONAL DEL AZUCAR DEL INGENIO LEDESMA')
    ,('OSPA','102300','OBRA SOCIAL DEL PERSONAL DEL AZUCAR DEL INGENIO SAN MARTIN')
    ,('OSPECA','103808','OBRA SOCIAL DEL PERSONAL DEL CAUCHO')
    ,('OSPEP','107107','OBRA SOCIAL DEL PERSONAL DEL ESPECTACULO PUBLICO')
    ,(NULL,'110206','OBRA SOCIAL DEL PERSONAL DEL JOCKEY CLUB DE ROSARIO')
    ,('OSPOCE','406','OBRA SOCIAL DEL PERSONAL DEL ORGANISMO DE CONTROL EXTERNO')
    ,('OSPPCYQ','114109','OBRA SOCIAL DEL PERSONAL DEL PAPEL, CARTON Y QUIMICOS')
    ,('OSDIC','400602','OBRA SOCIAL DEL PERSONAL DIRECTIVO DE LA INDUSTRIA DE LA CONSTRUCCION')
    ,('OSPG','109004','OBRA SOCIAL DEL PERSONAL GRAFICO')
    ,('OSJERA','1706','OBRA SOCIAL DEL PERSONAL JERARQUICO DE LA REPUBLICA ARGENTINA PARA EL PERSONAL JERARQUICO DE LA INDUSTRIA GRAFICA Y EL PERSONAL JERARQUICO DEL AGUA Y LA ENERGIA')
    ,(NULL,'2402','OBRA SOCIAL DEL PERSONAL JERARQUICO DEL TRANSPORTE AUTOMOTOR DE PASAJEROS DE CORDOBA Y AFINES')
    ,('OSPL','110305','OBRA SOCIAL DEL PERSONAL LADRILLERO')
    ,('OSPM','111803','OBRA SOCIAL DEL PERSONAL MARITIMO')
    ,(NULL,'109608','OBRA SOCIAL DEL PERSONAL MENSUALIZADO DEL JOCKEY CLUB DE BUENOS AIRES Y LOS HIPODROMOS DE PALERMO Y SAN ISIDRO')
    ,('OSPM','112707','OBRA SOCIAL DEL PERSONAL MOSAISTA')
    ,(NULL,'700108','OBRA SOCIAL DEL PERSONAL MUNICIPAL DE AVELLANEDA')
    ,(NULL,'700801','OBRA SOCIAL DEL PERSONAL MUNICIPAL DE LA MATANZA')
    ,('OSPENA','113403','OBRA SOCIAL DEL PERSONAL NAVAL')
    ,('OSPRERA','119302','OBRA SOCIAL DEL PERSONAL RURAL Y ESTIBADORES DE LA REPUBLICA ARGENTINA')
    ,('OSPS MERCEDES','112004','OBRA SOCIAL DEL PERSONAL SUPERIOR MERCEDES BENZ ARGENTINA')
    ,('OSPEA','100403','OBRA SOCIAL DEL PERSONAL SUPERIOR Y PROFESIONAL DE EMPRESAS AEROCOMERCIALES')
    ,('OSPTA','100700','OBRA SOCIAL DEL PERSONAL TECNICO AERONAUTICO')
    ,('OSPEGAP','115409','OBRA SOCIAL DEL PETROLEO Y GAS PRIVADOS')
    ,('OSMATA','111902','OBRA SOCIAL DEL SINDICATO DE MECANICOS Y AFINES DEL TRANSPORTE AUTOMOTOR')
    ,('OSSOELSAC','128409','OBRA SOCIAL DEL SINDICATO OBREROS Y EMPLEADOS DE EMPRESAS DE LIMPIEZA,SERVICIOS Y AFINES DE CORDOBA')
    ,('OSSURRBAC','128201','OBRA SOCIAL DEL SINDICATO UNICO DE RECOLECTORES DE RESIDUOS Y BARRIDO DE CORDOBA')
    ,(NULL,'1607','OBRA SOCIAL DEL SINDICATO UNIDO DE TRABAJADORES DE LA INDUSTRIA DE AGUAS GASEOSAS DE LA PROVINCIA DE SANTA FE')
    ,('OSEN','106609','OBRA SOCIAL ELECTRICISTAS NAVALES')
    ,('OSFFENTOS','125301','OBRA SOCIAL FEDERAL DE LA FEDERACION NACIONAL DE TRABAJADORES DE OBRAS SANITARIAS')
    ,('OSFE','1300','OBRA SOCIAL FERROVIARIA')
    ,('OSMA','112509','OBRA SOCIAL MODELOS ARGENTINOS')
    ,('OSMITA','402202','OBRA SOCIAL MUTUALIDAD INDUSTRIAL TEXTIL ARGENTINA')
    ,('DITEM','302106','OBRA SOCIAL PARA DIRECTIVOS, TECNICOS Y EMPLEADOS DE JOHN DEERE ARGENTINA')
    ,(NULL,'2303','OBRA SOCIAL PARA EL PERSONAL DE EMPRESAS DE  LIMPIEZA, SERVICIOS Y MAESTRANZA DE MENDOZA')
    ,(NULL,'701002','OBRA SOCIAL PARA EL PERSONAL MUNICIPAL DE TRES DE FEBRERO')
    ,('OSMAD','401308','OBRA SOCIAL PARA EL PERSONAL DE DIRECCION DE LA INDUSTRIA MADERERA')
    ,('OSEDEIV','402400','OBRA SOCIAL PARA EL PERSONAL DE DIRECCION DE LA INDUSTRIA VITIVINICOLA Y AFINES')
    ,('OSPES','123008','OBRA SOCIAL PARA EL PERSONAL DE ESTACIONES DE SERVICIO, GARAGES, PLAYAS DE ESTACIONAMIENTO, LAVADEROS AUTOMATICOS Y GOMERIAS DE LA REPUBLICA ARGENTINA')
    ,('OSIAD','100106','OBRA SOCIAL PARA EL PERSONAL DE LA INDUSTRIA ACEITERA, DESMOTADORA Y AFINES')
    ,('OSME','1201','OBRA SOCIAL PARA EL PERSONAL DEL MINISTERIO DE ECONOMIA Y DE OBRAS Y SERVICIOS PUBLICOS')
    ,(NULL,'4002','OBRA SOCIAL PARA EMPLEADOS Y PRODUCTORES DE ENTIDADES DE LA ACTIVIDAD AGROPECUARIA Y AGROALIMENTARIA DE LA ECONOMIA SOCIAL')
    ,('OSPLAD','1102','OBRA SOCIAL PARA LA ACTIVIDAD DOCENTE')
    ,('OSTEP','126106','OBRA SOCIAL PARA LOS TRABAJADORES DE LA EDUCACION PRIVADA')
    ,('OSPLA','115706','OBRA SOCIAL PARA PILOTOS DE LINEAS AEREAS COMERCIALES Y REGULARES')
    ,('OSPETAXR','128300','OBRA SOCIAL PEONES DE TAXIS DE ROSARIO')
    ,(NULL,'400701','OBRA SOCIAL PERSONAL DE DIRECCION DE LA INDUSTRIA CURTIDORA ARGENTINA')
    ,('OSPESCHA','127703','OBRA SOCIAL PERSONAL ESTACIONES DE SERVICIO,GARAGES,PLAYAS Y LAVADEROS DE LA PROVINCIA DEL CHACO')
    ,(NULL,'116709','OBRA SOCIAL PORTUARIOS  PUERTO SAN MARTIN Y BELLA VISTA')
    ,('OSPA','307','OBRA SOCIAL PORTUARIOS ARGENTINOS DE MAR DEL PLATA')
    ,('OSPROTURA','2105','OBRA SOCIAL PROFESIONALES DEL TURF DE LA REPUBLICA ARGENTINA')
    ,(NULL,'3603','OBRA SOCIAL PROGRAMAS MEDICOS SOCIEDAD ARGENTINA DE CONSULTORIA MUTUAL')
    ,('OSRM','302809','OBRA SOCIAL REFINERIAS DE MAIZ S.A.I.C.F.')
    ,('OSBA','126304','OBRA SOCIAL SERVICIOS SOCIALES BANCARIOS')
    ,(NULL,'303109','OBRA SOCIAL SUPERCO')
    ,('OSTAD','123107','OBRA SOCIAL TALLERISTAS A DOMICILIO')
    ,('OSTPCHPYARA','114307','OBRA SOCIAL TRABAJADORES  PASTELEROS, CONFITEROS, PIZZEROS , HELADEROS Y ALFAJOREROS DE LA REPUBLICA ARGENTINA')
    ,('OSPCN','125707','OBRA SOCIAL UNION PERSONAL DE LA UNION DEL  PERSONAL CIVIL DE LA NACION')
    ,('OSYPF','402509','OBRA SOCIAL YPF');
END

GO

IF NOT EXISTS (SELECT * FROM [dbo].[Anestesias])
BEGIN
    INSERT INTO [dbo].[Anestesias](Anestesia) VALUES
     ('Local')
    ,('Sedación leve (ansiólisis)')
    ,('Sedación moderada (sedación consciente)')
    ,('Sedación profunda (NLA)')
    ,('General');
END

GO

IF NOT EXISTS (SELECT * FROM [dbo].[Broncoscopios])
BEGIN
    INSERT INTO [dbo].[Broncoscopios](Modelo,NroPatrimonio,EsVideo,EsEBUS,Diametro,Canal) VALUES
     ('FUJINON EB-530S',NULL,1,0,'4.9','2.0');
END

GO

IF NOT EXISTS (SELECT * FROM [dbo].[Cargos])
BEGIN
    INSERT INTO [dbo].[Cargos](Cargo) VALUES
     ('Broncoscopista')
    ,('Asistente')
    ,('Anestesiólogo/a')
    ,('Patólogo/a');
END

GO

IF NOT EXISTS (SELECT * FROM [dbo].[Colores])
BEGIN
    INSERT INTO [dbo].[Colores](Color,Descripcion) VALUES
     ('#3bc9db','Anestesia Local')
    ,('#df5286','Anestesia General')
    ,('#9775fa','UCO/UTI/Guardia')
    ,('#ff8787','EBUS')
    ,('fdd835','Pendiente Confirmación')
    ,('#c0c0c0','Cancelado')
    ,('#69db7c','Adninistrativo');
END

GO

IF NOT EXISTS (SELECT * FROM [dbo].[Entornos])
BEGIN
    INSERT INTO [dbo].[Entornos](Entorno) VALUES
     ('Sala de Broncoscopía')
    ,('UTI')
    ,('UCO')
    ,('Guardia (Shockroom)')
    ,('Quirófano Central (piso 12)')
    ,('Quirófano Urología (piso 4)');
END

GO

IF NOT EXISTS (SELECT * FROM [dbo].[Indicaciones])
BEGIN
    INSERT INTO [dbo].[Indicaciones](Indicacion) VALUES
     ('Inspección de la vía aérea')
    ,('Rescate bacteriológico')
    ,('Rescate bacteriológico (paciente en ARM)')
    ,('Rescate bacteriológico (paciente inmunosuprimido HIV)')
    ,('Rescate bacteriológico (paciente inmunosuprimido oncohematológico)')
    ,('Rescate bacteriológico (paciente inmunosuprimido por intersticiopatía autoinmune)')
    ,('Rescate bacteriológico (paciente inmunosuprimido por otras enfermedades autoinmunes)')
    ,('Rescate bacteriológico (paciente inmunosuprimido por otras enfermedades no-autoinmunes)')
    ,('Sospecha de neoplasia')
    ,('Enfermedad el intesticio pulmonar)')
    ,('Hemóptisis')
    ,('Atelectasia')
    ,('Derrame pleural')
    ,('Neumotórax/neumomediastino')
    ,('Falta de reexpansión post-colocación de TAP')
    ,('Control de stent')
    ,('Control de traqueostomía')
    ,('Control post-cirugía de resección pulmonar/traqueal')
    ,('Control de fístula tráqueo-esofágica')
    ,('Decanulación')
    ,('Weaning dificultoso')
    ,('Evaluación vía aérea dificultosa (pre-qx')
    ,('Intubación guiada por fibrobroncoscopía')
    ,('Disfunción de cuerdas vocales')
    ,('Evaluación endoscópica de la deglución (FEES)')
    ,('Sindrome de apneas/hipopneas del sueño (SAHOS)')
    ,('Tos crónica')
    ,('Toilette bronquial post-broncoaspiración')
    ,('Lavado pulmonar en proteinosis alveolar');
END

GO

IF NOT EXISTS (SELECT * FROM [dbo].[Muestras])
BEGIN
    INSERT INTO [dbo].[Muestras](Muestra) VALUES
     ('Lavado broncoalveolar (BAL)')
    ,('Lavado/aspirado bronquial (LB)')
    ,('Biopsia trans-bronquial (BTB)')
    ,('Biopsia directa de lesión endobronquial')
    ,('Cepillado de lesión endobronquial')
    ,('Punción-aspiración de lesióm endobronquial (EBNA)')
    ,('Punción-aspiración de ganglio mediastinal (TBNA)')
    ,('Punción-aspiración de ganglio mediastinal ecoguiada (EBUS-TBNA)');
END

GO

IF NOT EXISTS (SELECT * FROM [dbo].[Determinaciones])
BEGIN
    INSERT INTO [dbo].[Determinaciones](Determinacion,Piso,Sector,EsDerivado,CentroReceptor,Comentarios) VALUES
     ('Bacteriología - Gérmenes comunes','1','C',0,NULL,NULL)
    ,('Bacteriología - Directo y cultivo para micobacterias','1','C',0,NULL,NULL)
    ,('Bacteriología - Cultivo rápido en medio líquido para M. tuberculosis (BACTEC MGIT 960)','1','C',0,NULL,NULL)    
    ,('Bacteriología - Xpert® MTB/RIF (Mycobacterium tuberculosis)','1','C',1,'Instituto Malbrán',NULL)
    ,('Micología - Directo y cultivo pata hongos (incluye Pneumocystis jirovecii)','3',NULL,0,NULL,NULL)
    ,('Micología - Ag. Aspergillus sp. (galactomananos)','3',NULL,0,NULL,NULL)
    ,('Virología - Panel virus respiratorios (ELISA)','6',NULL,0,NULL,NULL)
    ,('Virología - PCR SARS-CoV-2','6',NULL,0,NULL,NULL)
    ,('Virología - PCR Citomegalovirus (CMV)','6',NULL,0,NULL,NULL)
    ,('Virología - PCR Herpes simplex 1-2 (HSV)','6',NULL,0,NULL,NULL)
    ,('Virología - PCR Varicela (HZV)','6',NULL,0,NULL,NULL)
    ,('Citología - Recuento celular','1','B',0,NULL,NULL)
    ,('Citología - Extendido citológico oncológico','6',NULL,0,NULL,NULL)
    ,('Hematología - Citometría de flujo (CFC)','3',NULL,0,NULL,NULL);
END

GO

IF NOT EXISTS (SELECT * FROM [dbo].[Pendientes])
BEGIN
    INSERT INTO [dbo].[Pendientes](Pendiente) VALUES
     ('Laboratorio')
    ,('Laboratorio - hematocrito post-transfusión')
    ,('Laboratorio - coagulograma')
    ,('Laboratorio - esputo seriado para BAAR')
    ,('Autorización por obra social/prepago')
    ,('Revertir anticoagulación (hematología)')
    ,('Riesgo cardiológico')
    ,('Definir lugar de internación')
    ,('Transfundir hemoderivados')
    ,('Imagenes - Nueva tomografía computada')
    ,('Imagenes - PET-CT');
END

GO

IF NOT EXISTS (SELECT * FROM [dbo].[Personal])
BEGIN
    INSERT INTO [dbo].[Personal](Nombres,Apellidos,NroMatricula,NroLegajo,IdCargo) VALUES
     ('Estela','Becerra',NULL,NULL,2)
    ,('Hernan','Iannella',120466,166114,1);
END

GO

IF NOT EXISTS (SELECT * FROM [dbo].[Precauciones])
BEGIN
    INSERT INTO [dbo].[Precauciones](Precaucion) VALUES
     ('Anticoagulación')
    ,('Antiagregación con clopidogrel')
    ,('Plaquetopemia')
    ,('Urea plasmática elevada')
    ,('Menor de edad')
    ,('Retraso madurativo')
    ,('Hipoacusia')
    ,('Inmunocomprometido HIV')
    ,('Inmunocomprometido neutropénico')
    ,('Hipertesión pulmonar')
    ,('Sindrome de vena cava superior')
    ,('Hipertensión endocraneana')
    ,('Neumotorax/nemomediastino')
    ,('Trastorno psiquiátrico')
    ,('Médico/familiar de médico');
END

GO

IF NOT EXISTS (SELECT * FROM [dbo].[Servicios])
BEGIN
    INSERT INTO [dbo].[Servicios](Servicio) VALUES
     ('Clínica médica')
    ,('UTI')
    ,('UCO')
    ,('Guardia (Shockroom)')
    ,('Otorrinolaringología')
    ,('Pedriatría')
    ,('Cirugía torácica')
    ,('Cirugía oncológica');
END

GO
