CREATE TABLE [dbo].[Procedimientos]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY, 
    [IdPaciente] INT NOT NULL,
    [IdFicha] INT NOT NULL,
    [Fecha] DATE NOT NULL, 
    [IdEntorno] INT NOT NULL,
    [IdOperador] INT NOT NULL,
    [IdAyudante] INT NULL,
    [IdAsistente] INT NULL, 
    [IdAnestesiologo] INT NULL,
    [IdAnestesia] INT NULL, 
    [IdPatologo] INT NULL,
    [ROSE] bit NOT NULL,
    [IdBroncoscopio] INT NOT NULL, 
    [Informe] NVARCHAR(4000) NOT NULL, 
    [Comentarios] NVARCHAR(400) NULL, 
    [CapturaVideo] BIT NOT NULL, 
    CONSTRAINT [FK_Procedimientos_Paciente] FOREIGN KEY ([IdPaciente]) REFERENCES [Pacientes]([Id]),
    CONSTRAINT [FK_Procedimientos_Fichas] FOREIGN KEY ([IdFicha]) REFERENCES [Fichas]([Id]), 
    CONSTRAINT [FK_Procedimientos_Entornos] FOREIGN KEY ([IdEntorno]) REFERENCES [Entornos]([Id]),
    CONSTRAINT [FK_Procedimientos_Personal_1] FOREIGN KEY ([IdOperador]) REFERENCES [Personal]([Id]),
    CONSTRAINT [FK_Procedimientos_Personal_2] FOREIGN KEY ([IdAyudante]) REFERENCES [Personal]([Id]), 
    CONSTRAINT [FK_Procedimientos_Personal_3] FOREIGN KEY (IdAsistente) REFERENCES [Personal]([Id]),
    CONSTRAINT [FK_Procedimientos_Personal_4] FOREIGN KEY ([IdAnestesiologo]) REFERENCES [Personal]([Id]),
    CONSTRAINT [FK_Procedimientos_Personal_5] FOREIGN KEY ([IdPatologo]) REFERENCES [Personal]([Id]),
    CONSTRAINT [FK_Procedimientos_Anestesias] FOREIGN KEY ([IdAnestesia]) REFERENCES [Anestesias]([Id]),
    CONSTRAINT [FK_Procedimientos_Broncoscopios] FOREIGN KEY ([IdBroncoscopio]) REFERENCES [Broncoscopios]([Id]), 
    CONSTRAINT [AK_Procedimientos_IdFicha] UNIQUE ([IdFicha])
)
